name: Deploy Preview and Production Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      # build project artifacts and deploy to preview-production environment
      - run: npx vercel pull --yes --environment=preview-production --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpm run build
      - id: deploy-preview-production
        run: |
          npx vercel pull --yes --environment=preview-production --token=${{ secrets.VERCEL_TOKEN }}
          PREVIEW_DEPLOYMENT_URL=$(npx vercel deploy --prebuilt --target=preview-production --token=${{ secrets.VERCEL_TOKEN }})
          echo "PREVIEW_DEPLOYMENT_URL=$PREVIEW_DEPLOYMENT_URL" >> $GITHUB_OUTPUT

      # Run end-to-end tests with Playwright
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Run Playwright tests
        run: pnpm run e2e
        env:
          BASE_URL: ${{ steps.deploy-preview-production.outputs.DEPLOYMENT_URL }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
