name: Playwright Tests

on:
  push:
    branches-ignore:
      - main
  repository_dispatch:
    types:
      - "vercel.deployment.success"

jobs:
  run-e2es:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
