name: pull-request-end-to-end-tests-workflow

on:
  repository_dispatch:
    types:
      - "vercel.deployment.success"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  end-to-end-tests:
    name: pull-request-end-to-end-tests-job
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - name: Simulate pull requests end-to-end tests
        run: |
          echo "Demo pull-requests-end-to-end-tests"
          echo sha: "${{ github.event.client_payload.git.sha }}"
          echo url: "${{ github.event.client_payload.url }}"
